[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"

[headers]
"/" = {
  X-Frame-Options = "DENY",
  X-Content-Type-Options = "nosniff",
  X-XSS-Protection = "1; mode=block",
  Referrer-Policy = "strict-origin-when-cross-origin"
}

[headers "/index.html"]
Content-Type = "text/html"

[headers "/assets/*.js"]
Content-Type = "application/javascript"

[headers "/assets/*.css"]
Content-Type = "text/css"
